OCTOPUS-497 Bump CRS version from 2.0.10 to 2.0.11
octopusden/octopus-jira-utils pull request #6
Opened 2023-09-25 14:42 UTC by ozonophore

2023-09-25 14:45 UTC, aryabokon commented on components-registry/src/main/kotlin/org/octopusden/octopus/jira/config/ComponentRegistryServiceImpl.kt
> -import org.octopusden.octopus.components.registry.core.dto.*
за это отдельное спасибо

2023-09-25 15:11 UTC, aryabokon requested changes

2023-09-25 15:11 UTC, aryabokon commented on components-registry/src/main/kotlin/org/octopusden/octopus/jira/config/ComponentRegistryServiceImpl.kt
> +        val versionNames = VersionNames(
можно использовать function extension (.toModel()) и не придется полученный ответ мапить таким образом

2023-09-25 15:11 UTC, aryabokon commented on components-registry/src/main/kotlin/org/octopusden/octopus/jira/config/ComponentRegistryServiceImpl.kt
> +            vn.serviceBranch,
ниже описал

2023-09-25 16:01 UTC, CamaradeRoman approved these changes

2023-09-26 05:18 UTC, ozonophore commented on components-registry/src/main/kotlin/org/octopusden/octopus/jira/config/ComponentRegistryServiceImpl.kt
> +        val versionNames = VersionNames(
Честно говоря, мне не очень нравится этот подход с расширениями, он нарушает SOLID

2023-09-26 05:37 UTC, aryabokon commented on components-registry/src/main/kotlin/org/octopusden/octopus/jira/config/ComponentRegistryServiceImpl.kt
> +        val versionNames = VersionNames(
1. как-то не логично, что мы начнем холивар на эту тему, когда уже десяток маперов написаны таким образом и мы уперлись в еще один
2. Kotlin и Java очень противоречивые языки. Можно расценивать это как наследование с расширением без объявления. Нелогично не использовать функционал, когда все вокруг его будут использовать и уже давно используют

Наследование, кстати, тоже очень спорная вещь

2023-09-26 06:07 UTC, aryabokon approved these changes

2023-09-26 06:09 UTC, ozonophore commented on components-registry/src/main/kotlin/org/octopusden/octopus/jira/config/ComponentRegistryServiceImpl.kt
> +        val versionNames = VersionNames(
Исправил по требованию.

2023-09-26 06:09 UTC, ozonophore commented on components-registry/src/main/kotlin/org/octopusden/octopus/jira/config/ComponentRegistryServiceImpl.kt
> +            vn.serviceBranch,
Тут заменил на вызов первого метода

2023-09-26 06:13 UTC, merged